### ISSUE TITLE
Possibly wrong time complexity for BFS in CS2109S midterm cheatsheet

### ISSUE THREAD

**Issue by lithops-zty** [jasonqiu212/nus-cheatsheets#1]
Hi! First of all thannk you for providing high-quality cheatsheets that save my life! 

I noticed a possible error in your [CS2109S midterm cheatsheet](https://github.com/jasonqiu212/nus-cheatsheets/blob/main/CS2109S/cs2109s-midterm-cheatsheet.pdf). Namely, I think the time complexity for BFS should be $O(b^d)$ instead of $O(b^{d+1})$, since 

$$O(b^0 + b^1 + b^2 + \cdots + b^d)$$

$$=O\left(\frac{b^0\left(b^{d+1} - 1\right)}{b - 1}\right)$$

$$\approx O\left(\frac{b^{d+1}}{b}\right)$$

$$=O\left(b^d\right)$$

for large $b$ and $d$. 

Please correct me if I am wrong!

**Comment by jasonqiu212** [comment]
@lithops-zty Thanks for raising this issue! 

Yep, you are right. I will fix this mistake soon
